config/routes.rb
Rails.application.routes.draw do
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "artists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy!

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:pseudo, :profilp, :support, :description, :imagep, :insta, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.erb
<div id="<%= dom_id artist %>">


<div class="centrageI" >
<div class="card-show mb-3" style="max-width: 100%;">
  <div class="row g-0">
    
    <div class="col-md-4" style="height: 100%;" >
    <div class="CentragePdP">
      <img src="<%= artist.imagep %>" style="width:100%;">
    </div>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <br>
        <h5 class="card-title"><%= artist.pseudo %></h5>
        <ul>
        <p class="card-text"><%= artist.support %></p>
        <p class="card-text"><%= artist.description %></p>
        <p>
    <strong>Insta:</strong>
    <a class="DecoB" href="<%= artist.insta %>"><%= artist.insta %></a>
        </p>

        <p>
    <strong>Link:</strong>
    <a class="DecoB" href="<%= artist.link %>"><%= artist.link %></a>
        </p>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <% if artist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group" style="padding-left:10vw">
    <%= form.label :pseudo, style: "display: block" %>
    <div class="col-md-6">
    <%= form.text_field :pseudo, class: "form-control" %>
  </div>  </div>


  <div class="form-group" style="padding-left:10vw">
    <%= form.label :profilp, style: "display: block" %>
    <div class="col-md-6">
    <%= form.text_area :profilp, class: "form-control" %>
  </div>  </div>


  <div class="form-group" style="padding-left:10vw">
    <%= form.label :support, style: "display: block" %>
    <div class="col-md-6">
    <%= form.text_field :support, class: "form-control" %>
  </div>  </div>


  <div class="form-group" style="padding-left:10vw">
    <%= form.label :description, style: "display: block" %>
    <div class="col-md-6">
    <%= form.text_area :description, class: "form-control" %>
  </div>  </div>


  <div class="form-group" style="padding-left:10vw">
    <%= form.label :imagep, style: "display: block" %>
    <div class="col-md-6">
    <%= form.text_area :imagep, class: "form-control" %>
  </div>  </div>


  <div class="form-group" style="padding-left:10vw">
    <%= form.label :insta, style: "display: block" %>
    <div class="col-md-6">
    <%= form.text_field :insta, class: "form-control" %>
  </div>  </div>


  <div class="form-group" style="padding-left:10vw">
    <%= form.label :link, style: "display: block" %>
    <div class="col-md-6">
    <%= form.text_field :link, class: "form-control" %>
  </div>  </div>
  <br>
  <div style="padding-left:10vw">

<%= form.submit class: "btn btn-primary" %>
  </div>

  <% end %>

app/views/artists/_mentionlegales.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spynelle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <header>
        <h1>Spynelle</h1>
        <nav>
            <ul>
                <li><a href="home">Home</a></li>
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
                <li><a href="artists">Artists</a></li>
            </ul>
        </nav>
    </header>
        <main>
        <section>
            <h2>Mentions Légales</h2>
            <p>Ce site est édité par Spynelle.</p>
            <p>Adresse : 1 rue Jacques Ellul Bordeaux 33000</p>
            <p>Numéro de téléphone : 0123456789</p>
            <p>Email : mail@spynelle.com</p>
        </section>

        <section>
            <h3>Responsable de la publication</h3>
            <p>Spynelle</p>
        </section>

        <section>
            <h3>Hébergement</h3>
            <p>Le site est hébergé par Scalingo</p>
        </section>
    </main>
    <%= yield %>
    <footer>
        <p>&copy; 2024 Spynelle, Tous droits réservés.</p>
    </footer>
  </body>
</html>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>



<%= render "form", artist: @artist %>
</div>

<br>

<div class="buttonS2">

<button type="button" class="btn btn-dark"><%= link_to "Show this artist", @artist %></button>
<button type="button" class="btn btn-dark"><%= link_to "Back to artists", artists_path %></button>
</div>

app/views/artists/index.html.erb
<p style="color: green"><%= notice %></p>
<br>
<br>


      <div class="centrageD">
<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-lg-3">
      <div class="card">
        <img src="<%= artist.profilp %>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title"><strong><%= artist.pseudo %></strong></h5>
          <p class="card-text"><%= artist.description %></p>
          <div class="bouton-show">
          <%= link_to "Show this artist", artist, class: "btn btn-dark" %>
        </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
  </div>
  <div class="buttonS">
    
 <button type="button" class="btn btn-dark"><%= link_to "New artist", new_artist_path %></button>

 </div>

app/views/artists/new.html.erb
<h1>New artist</h1>
<div class="DecoE">
<%= render "form", artist: @artist %>
</div>

<br>

<div class="buttonS">
  <button type="button" class="btn btn-dark"><%= link_to "Back to artists", artists_path %></button>

</div>

app/views/artists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artist %>

<div class="buttonS3">
  <button type="button" class="btn btn-dark"><%= link_to "Edit this artist", edit_artist_path(@artist) %></button>
  <button type="button" class="btn btn-dark"><%= link_to "Back to artists", artists_path %></button>
  <div class="buttonD">
  <%= button_to "Delete this artist", @artist, method: :delete %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spynelle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <header>
      <a class="logo" href="/">
        <%= image_tag 'logo_spynelle.svg' %>
        </a>
        <a class="" href="/">
        <h1>Spynelle</h1>
        </a>
        
        <nav>
            <ul>
                <li><a href="artists">Artists</a></li>
            </ul>
        </nav>
    </header>
    <%= yield %>
    

  </body>
    <footer>
        <p> 2024 Spynelle, Tous droits réservés.</p>
        <a href="mentionlegales">Mention légales</a>
    </footer>

</html>